### ISSUE TITLE
I could not download the class: https://www.coursera.org/learn/responsivedesign

### ISSUE THREAD

**Issue by codiceexerceo** [coursera-dl/coursera-dl#463]
https://www.coursera.org/learn/responsivedesign

I cannot download the materials for the above class.  I assume the class name is responsivedesign.

**Comment by balta2ar** [comment]
I've just downloaded the course without any problems.

Please see this section on how to report issues in this repository: https://github.com/coursera-dl/coursera-dl#filing-an-issuereporting-a-bug

**Comment by findways** [comment]
balta2ar
would you mind showing how you did that?
Thanks

**Comment by balta2ar** [comment]
```
coursera-dl --aria -n --path . responsivedesign
```

You don't have to use `--aria` and `-n` options, though.

**Comment by codiceexerceo** [comment]
I am not sure what is wrong:

Downloading class: responsivedesign
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/responsivedesign
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/responsivedesign (23904 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering supplement URLs for element_id <ZiQZT>.
Gathering supplement URLs for element_id <ssiNo>.
Gathering supplement URLs for element_id <zkVnX>.
Gathering video URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Proceeding with download of resolution 540p of <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering subtitle URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering transcript URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering video URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Proceeding with download of resolution 540p of <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering subtitle URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering transcript URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering video URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Proceeding with download of resolution 540p of <qvomt-xEEeWYIQ7qEqibNw>.
Gathering subtitle URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Gathering transcript URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/Library/Python/2.7/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/Library/Python/2.7/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/Library/Python/2.7/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by balta2ar** [comment]
@codiceexerceo Use the latest version from github. This issue was solved very recently.

**Comment by codiceexerceo** [comment]
I am not exactly sure how to do that.  Do I use pip?  I am on mac.  Are there instructions on how to install the latest version from github.

**Comment by codiceexerceo** [comment]
This issue has not been resolved.  I don't know why it has been closed:

coursera-dl -u codice.exerceo@gmail.com -p 1saline5 responsivedesign
Downloading class: responsivedesign
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/responsivedesign
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/responsivedesign (23904 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering supplement URLs for element_id <ZiQZT>.
Gathering supplement URLs for element_id <ssiNo>.
Gathering supplement URLs for element_id <zkVnX>.
Gathering video URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Proceeding with download of resolution 540p of <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering subtitle URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering transcript URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering video URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Proceeding with download of resolution 540p of <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering subtitle URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering transcript URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering video URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Proceeding with download of resolution 540p of <qvomt-xEEeWYIQ7qEqibNw>.
Gathering subtitle URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Gathering transcript URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Traceback (most recent call last):
  File "/Users/SK/ZCode/coursera_virtual_env/venv/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by balta2ar** [comment]
@codiceexerceo The issue has been closed because it had been resolved by a recent commit. However, pip version of this script is outdated and does not contain the fix. For this reason I offered you to use version from github.

Please check these instructions on how to install coursera-dl from github: https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

**Comment by sa1987** [comment]
Dear Team,

I have downloaded and used the github version only. Issue persist for only selected courses. Its working fine for quantitative methods but not for Measuring Causal Effects in the Social Sciences or data scientist's toolbar.

For more details.PLs refer tkt#473.
