### ISSUE TITLE
How to download a course with "new deisgn"?

### ISSUE THREAD

**Issue by Make42** [coursera-dl/coursera-dl#475]
### Courses are not found with new naming convention

I would like to download the material from
https://www.coursera.org/learn/machinelearningwithbigdata/
Recently coursera updated their design and with it its course-naming conventions as it seems:

:~$ coursera-dl -u <myemail> -p <mypass> machinelearningwithbigdata
Downloading class: machinelearningwithbigdata
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found
Could not find class: machinelearningwithbigdata

### My environment
* Operating System (name/version): Kubuntu 14.4
* Python version: Python 2.7.6, Python 3.4.3 (not sure which is used by coursera-dl)
* coursera-dl version: Not sure how to display this - I did `pip install coursera` and `pip3 install coursera`

**Comment by balta2ar** [comment]
This issue is fixed in github version of the script. Please don't use pip version at the moment, use the latest version from github.

**Comment by Make42** [comment]
https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems is what I did now. But it still does not work, getting the same error.

**Comment by balta2ar** [comment]
Please make sure you're using github version (check your PYTHONPATH or something). I can download this course just fine.

**Comment by Make42** [comment]
Now I get the error:

```
Downloading class: machinelearningwithbigdata
Starting new HTTPS connection (1): class.coursera.org
~/coursera-download/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
~/coursera-download/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
404 Client Error: Not Found for url: https://class.coursera.org/machinelearningwithbigdata
Starting new HTTPS connection (1): www.coursera.org
~/coursera-download/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "~/coursera-download/coursera/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "~/coursera-download/coursera/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "~/coursera-download/coursera/coursera/coursera_dl.py", line 973, in download_on_demand_class
    login(session, args.username, args.password)
  File "~/coursera-download/coursera/coursera/cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "~/coursera-download/local/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "~/coursera-download/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "~/coursera-download/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "~/coursera-download/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send                                                                               
    raise SSLError(e, request=request)                                                                                                                                                                    
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

**Please open the thread again - until really resolved.**

**Comment by balta2ar** [comment]
@Make42 I keep the issue resolved because none of the errors you have reported so far are new. We know about them, we've seen them. There is no point to duplicate issues.

The SSLError problem is also known. It's been reported many times. Please search over both open and closed tickets to find the solution. You may start here: https://github.com/coursera-dl/coursera-dl/issues/383

**Comment by gokul-uf** [comment]
@balta2ar  I get the same errors as @Make42

**Comment by Make42** [comment]
@gokul-uf: This worked for me:

```
mkdir mycoursera; cd mycoursera
sudo easy_install virtualenv
virtualenv -p /usr/bin/python3 coursera
cd coursera/
./bin/pip install coursera
./bin/coursera-dl -u username@provider.com -p password mycourse
```
